config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  resources :menu
  resources :customers
  resources :users
  resources :orders
  resources :order_items
  resources :menu_items
  resources :admin_menu
  get "add_toCart/:id" => "menu_items#update"
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/dashboard" => "dashboard#index"
  get "/history" => "orders#history", as: :history
  get "/pendingorders" => "orders#orderupdate"
  post "/change_status/:id" => "orders#change_status"
  get "/singleorder/:id" => "orders#show"
  get "/edit_menu" => "admin_menu#edit_menu"
  get "add_items/:id" => "admin_menu#add_items"
  get "add_cat/:id" => "admin_menu#add_cat"
  get "add_user" => "admin_menu#add_user"
  get "add_admin/:id" => "admin_menu#add_admin"
  get "add_clerk/:id" => "admin_menu#add_clerk"
end

app/models/admin_menu.rb
class AdminMenu < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  has_secure_password
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base
  has_many :menu_items

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_many :order_items
  belongs_to :menu_category

end

app/models/order.rb
class Order < ActiveRecord::Base
  #has_many :order_items
  #belongs_to :user
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :menu_item

  def self.of_user(user)
    all.where(user_id: user.id)
  end

end

app/controllers/admin_menu_controller.rb
class AdminMenuController < ApplicationController

  def index
    render "index"
  end

  def edit_menu
    render "add_new"
  end

  def add_items
    id = params[:id]
    item = MenuItem.find(id)
    if item.available == true
      item.available = false
      item.save
    else
      item.available = true
      item.save
    end
    redirect_to "/edit_menu"
  end

  def add_cat
    id = params[:id]
    item = MenuCategory.find(id)
    if item.available == true
      item.available = false
      item.save
    else
      item.available = true
      item.save
    end
    redirect_to "/edit_menu"
  end

  def add_user
    render "add_user"
  end

  def add_admin
    id = params[:id]
    item = Customer.find(id)
    item.role = "admin"
    item.save
    redirect_to "/add_user"
  end

  def add_clerk
    id = params[:id]
    item = Customer.find(id)
    item.role = "clerk"
    item.save
    redirect_to "/add_user"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      flash[:error] = "Kindly sign up/sign in first."
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    @current_user_id = session[:current_user_id]
    if @current_user_id
      @current_user = Customer.find(@current_user_id)
    else
      nil
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "customers/new"
  end

  def create
    customer = Customer.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      role: "customer" )
      if customer.save
        session[:current_user_id] = customer.id
        redirect_to "/dashboard"
      else
        flash[:error] = customer.errors.full_messages.join(", ")
        redirect_to new_customer_path
      end
  end

  def destroy
    id = params[:id]
    user = Customer.find(id)
    user.destroy
    redirect_to "/"
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController


  def index
    render "index"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render "index"
  end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

  def index
    render "index"
  end

  def create
    new_category = MenuCategory.new(name: params[:name], available: true)
    if new_category.save
      flash[:error] = "New Category Successfully Created."
      redirect_to admin_menu_index_path
    end
  end

  def destroy
    id = params[:id]
    OrderItem.where(id: id).destroy_all
    redirect_to "/menu"
  end

  def update
    id = params[:id]
    orderItem = OrderItem.find(id)
    actual = orderItem.menu_item_quatity.to_i
    update = params[:menu_item_quatity].to_i
    unless actual == 1 and update == -1
      orderItem.menu_item_quatity = actual + update
      unless orderItem.save
        flash[:error] = orderItem.errors.full_messages.join(", ")
      end
    else
      orderItem.destroy
    end
    redirect_to "/menu"
  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def create
    menu_cat = params[:menu]
    menu_category = MenuCategory.where(name: menu_cat)[0]
    mc_id = menu_category.id
    new_item = MenuItem.new(menu_category_id: mc_id, name: params[:name], description: params[:description], price: params[:price], available: true)
    if new_item.save
      flash[:error] = "Menu Item added successfully."
      redirect_to admin_menu_index_path
    else
      flash[:error] = customer.errors.full_messages.join(", ")
      redirect_to admin_menu_index_path
    end
  end

  def update
    temp = OrderItem.where(menu_item_id: params[:id], user_id: @current_user.id)
    order = MenuItem.find(params[:id])
    if temp.count == 0
      new_order = OrderItem.create!(menu_item_id: order.id,
                                    menu_item_name: order.name,
                                    menu_item_price: order.price,
                                    menu_item_quatity: 1,
                                    user_id: @current_user.id)
    else
      flash[:error] = "Item already in cart."
    end
    redirect_to "/menu"
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @total = 0
    render "new"
  end

  def create
    new_order = Order.create!(date: Date.today, user_id: @current_user.id, status: "pending", cost: session[:total_cost])
    flash[:error] = "Order placed successfully!"
    OrderItem.where(user_id: @current_user.id).destroy_all
    redirect_to "/dashboard"
  end

  def history
    render "history"
  end

  def orderupdate
    render "pendingorders"
  end

  def change_status
    id = params[:id]
    order = Order.find(id)
    order.status = "delivered"
    order.save
    redirect_to "/pendingorders"
  end

  def show
    render "singleorder"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    customer = Customer.find_by(email: params[:email])
    if customer && customer.authenticate(params[:password])
      session[:current_user_id] = customer.id
      redirect_to "/dashboard"
    else
      flash[:error] = "Your login attempt was invalid. Please try again."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin_menu/add_new.html.erb
<div class="container">
  <div class="MenuBackground">
    <div class="row">
      <div class="col-xs-12">
        <br>
        <h1 class="card-title text-center">Menu Items</h1>
        <% MenuCategory.all.each do |category| %>
          <% menuItems = MenuItem.where(menu_category_id: category.id) %>
          <% unless menuItems.count == 0 %>
            <div class="table-responsive">
              <center><h3 class="MenuTitle"><%= category.name.upcase %></h3></center>
              <table class="table table-shopping">
                <thead>
                  <tr class="text-center">
                    <th>Serial Number</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Status</th>
                  </tr>
                </thead>

                <tbody>
                  <% index = 1 %>
                  <% menuItems.each do |menu| %>

                    <tr class="text-center">
                      <td><%= index %></td>
                          <% index += 1 %>
                      <td><%= menu.name %></td>
                      <td><%= menu.description %></td>
                      <td>₹ <%= menu.price %></td>
                      <td>
                        <% if menu.available == true %>
                          <%= form_with url: "/add_items/#{menu.id}", method: "get"  do |form| %>
                          <%= form.submit "Marks as unavailable", class: "btn btn-danger" %>
                          <% end %>
                        <% else %>
                          <%= form_with url: "/add_items/#{menu.id}", method: "get"  do |form| %>
                          <%= form.submit "Marks as available.", class: "btn btn-primary" %>
                          <% end %>
                        <% end %>
                      </td>
                      </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
</div>
<br><br><br><br><br><br><br><br><br><br>
<div class="container">
  <div class="MenuBackground">
    <div class="row">
      <div class="col-xs-12">
        <br>
        <h1 class="card-title text-center">All Menu Categories</h1>
        <% index = 1 %>
        <% menuCat = MenuCategory.all %>
        <% menuCat.each do |menu| %>
          <div class="table-responsive">
            <table class="table table-shopping">
              <thead>
                <tr class="text-center">
                  <th>Serial Number</th>
                  <th>Name</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <tr class="text-center">
                  <td><%= index %></td><% index += 1 %>
                  <td><%= menu.name %></td>
                  <td>
                    <% if menu.available == true %>
                      <%= form_with url: "/add_cat/#{menu.id}", method: "get"  do |form| %>
                      <%= form.submit "Marks as unavailable", class: "btn btn-danger" %>
                      <% end %>
                    <% else %>
                      <%= form_with url: "/add_cat/#{menu.id}", method: "get"  do |form| %>
                      <%= form.submit "Marks as available.", class: "btn btn-primary" %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br><br><br><br><br><br><br><br><br><br>

app/views/admin_menu/add_user.html.erb
<div class="container">
  <div class="MenuBackground">
    <div class="row">
      <div class="col-xs-12">
        <br>
        <h1 class="card-title text-center">All Users</h1>
        <% index = 1 %>
        <% users = Customer.all %>
          <div class="table-responsive">
            <table class="table table-shopping">
              <thead>
                <tr class="text-center">
                  <th>Serial Number</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
              <% users.each do |user| %>
                <tr class="text-center">
                  <td><%= index %></td><% index += 1 %>
                  <td><%= user.first_name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.role.capitalize %></td>
                  <td>
                    <% if user.role == "clerk" %>
                      <%= form_with url: "/add_admin/#{user.id}", method: "get"  do |form| %>
                      <%= form.submit "Promote to Admin", class: "btn btn-danger" %>
                      <% end %>
                    <% end %>
                    <% if user.role == "admin" %>
                      <%= form_with url: "/add_clerk/#{user.id}", method: "get"  do |form| %>
                      <%= form.submit "Move to Clerk", class: "btn btn-primary" %>
                      <% end %>
                    <% end %>
                    <% if user.role == "customer" %>
                    <div style="display: inline;">
                        <%= form_with url: "/add_clerk/#{user.id}", method: "get"  do |form| %>
                        <%= form.submit "Promote to Clerk", class: "btn btn-primary" %>
                        <% end %>
                        <%= form_with url: "/add_admin/#{user.id}", method: "get"  do |form| %>
                        <%= form.submit "Promote to Admin", class: "btn btn-small btn-danger" %>
                        <% end %>
                      </div>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>
<br><br><br><br><br><br><br>

app/views/admin_menu/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-4 col-md-offset-4">
    <p class="UsersNew-title">Add a new Menu Category</p>
<section class="UsersNew">
<%= form_with url: menu_index_path do |form| %>
<div class="FormSection">
  <p><center class="FormInput-label">Category Name</center></p>
  <center><%= form.text_field :name, class: "Form-Input" %></center>
</div>
<div class="FormSection">
<center><%= form.submit "ADD", class: "FormSubmit" %></center>
</div>
<% end %>
</section>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-xs-12 col-md-4 col-md-offset-4">
    <p class="UsersNew-title">Add a new Menu Item</p>
<section class="UsersNew">
<%= form_with url: menu_items_path do |form| %>
<div class="FormSection">
  <p><center class="FormInput-label">To which menu category does this item belong?</center></p>
  <center>
  <% menu = MenuCategory.all %>
    <select name="menu" class="FormInput-lael">
    <% menu.each do |menu| %>
      <option value="<%= menu.name %>"><%= menu.name %></option>
      <% end %>
    </select>
  </center>
</div>
<div class="FormSection">
  <p><center class="FormInput-label">Name</center></p>
  <center><%= form.text_field :name, class: "Form-Input" %></center>
</div>
<div class="FormSection">
  <p><center class="FormInput-label">Description</center></p>
  <center><%= form.text_field :description, class: "Form-Input" %></center>
</div>
<div class="FormSection">
  <p><center class="FormInput-label">Price</center></p>
  <center><%= form.text_field :price, class: "Form-Input" %></center>
</div>
<div class="FormSection">
<center><%= form.submit "ADD", class: "FormSubmit" %></center>
</div>
<% end %>
</section>
  </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-xs-12 col-md-4 col-md-offset-4">
    <p class="UsersNew-title">Welcome new User!<br>To make online orders, you need to create an account first.</p>
<section class="UsersNew">
<%= form_with url: customers_path do |form| %>
<div class="FormSection">
  <p><center class="FormInput-label">First Name</center></p>
  <center><%= form.text_field :first_name, class: "Form-Input" %></center>
</div>
<div class="FormSection">
  <p><center class="FormInput-label">Last name</center></p>
  <center><%= form.text_field :last_name, class: "Form-Input" %></center>
</div>
<div class="FormSection">
  <p><center class="FormInput-label">Email</center></p>
  <center><%= form.email_field :email, class: "Form-Input" %></center>
</div>
<div class="FormSection">
  <p><center class="FormInput-label">Password</center></p>
  <center><%= form.password_field :password, class: "Form-Input" %></center>
</div>
<div class="FormSection">
<center><%= form.submit "Sign Up!", class: "FormSubmit" %></center>
</div>
<% end %>
</section>
  </div>
</div>
<br><br><br><br><br>

app/views/dashboard/index.html.erb
<div class="DashboardButton">
  <h3><%= link_to "Make an Order", "/menu", class: "DashboardText" %></h3>
</div>
<br>

<div class="DashboardButton">
  <h3><%= link_to "Check Order History", "/history", class: "DashboardText" %></h3>
</div>
<br>

<% if @current_user.role == "clerk" or @current_user.role == "admin" %>
  <div class="DashboardButton">
  <h3><%= link_to "Review pending orders", "/pendingorders", class: "DashboardText" %></h3>
  </div>
<br>
<% end %>

<% if @current_user.role == "admin" %>
  <div class="DashboardButton">
  <h3><%= link_to "Add new menu items.", admin_menu_index_path, class: "DashboardText" %></h3>
  </div>
  <br>
  <div class="DashboardButton">
  <h3><%= link_to "Edit existing menu.", "/edit_menu" , class: "DashboardText" %></h3>
  </div>
  <br>
  <div class="DashboardButton">
  <h3><%= link_to "Add a new Admin/Clerk", "/add_user", class: "DashboardText" %></h3>
  </div>
  <br>
<% end %>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/home/index.html.erb
<head>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<div class="row">
	<div class="col-xs-12">
		<div id="banner-img">
			<div class="container">
				<center>
					<div id="banner-content">
						<h1 class="HomeTitle">WELCOME TO THE CENTRAL PERK CAFE</h1>
						<p class="HomeAuthenticate">If you are a new user,<%= link_to " Sign Up Here.", new_customer_path, class: "HomeLink" %></p>
						<p class="HomeAuthenticate">If you are an existing user,<%= link_to " Sign In Here.", new_session_path, class: "HomeLink" %></p>
					</div>
				</center>
			</div>
		</div>
	</div>
</div>
<br><br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Central Perk Cafe</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,500&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fuggles&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=STIX+Two+Math&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('coffee.ico') %>
  </head>

  <body class="container">
  <br><br><br>
	<% if @current_user %>
  <h3 class="PageTitle">Welcome <%= @current_user.first_name %>.
	<%= link_to "Sign Out", destroy_session_path, method: "delete", class: "SignOutLink" %></h3>
	<% end %>
	<% if flash[:error] %>
		<p class="FlashError"><%= flash[:error] %></p>
	<% end %>
  <nav class="navbar navbar-expand-md navbar-light navbar-fixed-top NavbarTop">
  <% if @current_user %>
    <%= link_to "Central Perk", "/dashboard", class: "navbar-brand NavTitle" %>
  <% else %>
    <%= link_to "Central Perk", "/", class: "navbar-brand NavTitle" %>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-right NavList">
      <li class="nav-item">
      </li>
      <li class="nav-item NavItem">
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  <footer class="nav-color navbar-fixed-bottom">
	<div class="container">
		<center>
			<p class="FooterText">Copyright © Cafeteria Management. All Rights Reserved | Contact Us: +91-9870661375</p>
		</center>
	</div>
</footer>
  </body>
</html>

app/views/menu/index.html.erb
<div class="MenuBackground2">
        <div class="row">
          <div class="col-xs-12">
            <br>
            <h1 class="card-title text-center PageTitle2">Menu</h1>
            <% MenuCategory.where(available: true).each do |category| %>
              <% menuItems = MenuItem.where(menu_category_id: category.id, available: true) %>
              <% unless menuItems.count == 0 %>

                <div class="table-responsive">
                  <center><h3 class="MenuTitle"><%= category.name.upcase %></h3></center>
                  <table class="table table-shopping">
                    <thead>
                      <tr class="text-center">
                        <th>Serial Number</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Add</th>
                      </tr>
                    </thead>

                    <tbody>
                      <% index = 1 %>
                      <% menuItems.each do |menu| %>

                        <tr class="text-center">
                          <td><%= index %></td>
                              <% index += 1 %>
                          <td><%= menu.name %></td>
                          <td><%= menu.description %></td>
                          <td>₹ <%= menu.price %></td>
                          <td><%= form_with url: "add_toCart/#{menu.id}", method: "get"  do |form| %>
                                <%= form.submit "Add to Cart", class: "btn btn-primary" %>
                              <% end %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <hr/>
              <% end %>
            <% end %>
          </div>
          </div>
        </div>
      </div>
</div>
<hr>
<div class="MenuBackground">
  <% orderitems = OrderItem.where(user_id: @current_user.id) %>
  <center><h1>Your Cart</h1></center>
  <div class="table-responsive">
    <table class="table table-shopping">
      <thead>
        <tr class="text-center">
          <% index = 1 %>
          <th>Serial Number</th>
          <th>Item Name</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
      <% total = 0 %>
        <% orderitems.each do |order| %>
          <tr class="text-center">
            <td><%= index %></td>
            <% index = index + 1 %>
            <td><%= order.menu_item_name %></td>
            <td>₹ <%= order.menu_item_price %></td>
            <td>
            <div class="btn-group btn-group-sm" style="display: flex;">
              <%= form_with(url: "/menu/#{order.id}", method: "put") do |form| %>
                <%= form.hidden_field :menu_item_quatity, value: -1 %>
                <button class="btn btn-link btn-info"> <i class="material-icons">remove</i> </button>
              <% end %>
              <%= order.menu_item_quatity %>
              <%= form_with(url: "/menu/#{order.id}", method: "put") do |form| %>
                <%= form.hidden_field :menu_item_quatity, value: 1 %>
                <button class="btn btn-link btn-info"> <i class="material-icons">add</i> </button>
              <% end %>
            </div>
            <% total = total + order.menu_item_price * order.menu_item_quatity %>
            </td>
            <td>
              <%= form_with url: "/menu/#{order.id}", method: "delete"  do |form| %>
                <%= form.submit "Remove from Cart", class: "btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="ShopCart-total">
     <h2>Total: ₹ <%= total %> /-</h2>
     </div>
    <div>
      <h3 class="ShopCart-checkout"><%= link_to "Checkout", orders_path, class: "CheckoutText" %></h3>
    </div>
  </div>
</div><br><br><br><br><br><br><br><br><br><br><br>

app/views/orders/history.html.erb
<div class="MenuBackground">
        <div class="row">
          <div class="col-xs-12">
            <br>
            <h1 class="card-title text-center">Your Order History</h1>
            <% index = 1 %>
            <% Order.where(user_id: @current_user.id).each do |orders| %>
                <div class="table-responsive">
                  <table class="table table-shopping">
                    <thead>
                      <tr class="text-center">
                        <th>Serial Number</th>
                        <th>Order Date</th>
                        <th>Cost</th>
                        <th>Delivery Status</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr class="text-center">
                          <td><%= index %></td>
                              <% index += 1 %>
                          <td><%= orders.date.to_s(:long) %></td>
                          <td>₹ <%= orders.cost %></td>
                          <td><%= orders.status.upcase %></td>
                          </tr>
                    </tbody>
                  </table>
                </div>
            <% end %>
          </div>
          </div>
        </div>
      </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/orders/new.html.erb
<div class="MenuBackground">
  <% orderitems = OrderItem.where(user_id: @current_user.id) %>
  <center class="ShopCart-header"><h1>Your Cart</h1></center>
  <div class="table-responsive">
    <table class="table table-shopping">
      <thead>
        <tr class="text-center">
          <% index = 1 %>
          <th>SR No.</th>
          <th>Item Name</th>
          <th>Price</th>
        </tr>
      </thead>

      <tbody>
        <% orderitems.each do |order| %>
          <tr class="text-center">
            <td><%= index %></td>
            <% index = index + 1 %>
            <td><%= order.menu_item_name %></td>
            <td>₹ <%= order.menu_item_price %></td>
            <% @total = @total + order.menu_item_price %>
            </tr>
        <% end %>
      </tbody>
    </table>
    <div class="ShopCart-total">
     <h2>Total: ₹ <%= @total %> /-</h2>
     <% session[:total_cost] = @total %>
     </div>
    <div>
      <h3 class="ShopCart-checkout"><%= link_to "Go back to Menu", "/menu", class: "CheckoutText" %></h3>
    </div>
    <div>
      <h3 class="ShopCart-checkout"><%= link_to "Place Order", orders_path, method: "post", class: "CheckoutText" %></h3>
    </div>
  </div>
</div><br><br><br><br><br><br><br><br><br><br><br>